# 配置文件的键名命名方式统一使用小驼峰。

# HTTP Server.
server:
  address:     ":8000"
  sessionPath: "temp/sessions"    # Session文件存储目录
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

# 数据库连接配置
database:
  logger:
    path:    "logs/sql"
    level:   "all"
    stdout:  true
    ctxKeys: ["RequestId"]

  default:
    link:   "mysql:root:123456@tcp(127.0.0.1:3306)/gf_ruoyi"
    debug:  true

# Logger configurations.
logger:
  path:    "logs/default"
  level:   "all"
  stdout:  true
  ctxKeys: ["RequestId"]

# 工具相关配置
gfcli:
  # dao生成
  gen: 
    dao:
    - link: "mysql:root:123456@tcp(127.0.0.1:3306)/gf_ruoyi"
      # tables: "sys_user"
      
