// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import(
"github.com/gogf/gf/v2/frame/g"
"github.com/gogf/gf/v2/os/gtime"
)

// SysUserForDao is the golang structure of table sys_user for DAO operations like Where/Data.
type SysUser struct {
g.Meta `orm:"dto:true"`
    UserId interface{} // 用户ID                   
    UserName interface{} // 用户账号                 
    NickName interface{} // 用户昵称                 
    Password interface{} // 登录密码                 
    Mobile interface{} // 手机号                   
    Avatar interface{} // 用户头像地址             
    Status interface{} // 用户状态；0:禁用,1:正常  
    RoleIds interface{} // 角色id字符串             
    ShopIds interface{} // 店铺ID字符串             
    DeptId interface{} // 部门ID                   
    Remark interface{} // 备注                     
    CreatedAt *gtime.Time // 创建时间                 
    UpdatedAt *gtime.Time // 更新时间                 
    DeletedAt *gtime.Time // 删除时间                 
}