// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import(
"github.com/gogf/gf/v2/frame/g"
"github.com/gogf/gf/v2/os/gtime"
)

// SysUserOnlineForDao is the golang structure of table sys_user_online for DAO operations like Where/Data.
type SysUserOnline struct {
g.Meta `orm:"dto:true"`
    Id interface{} //            
    Token interface{} // 用户token  
    UserName interface{} // 用户名     
    Ip interface{} // 登录ip     
    Explorer interface{} // 浏览器     
    Os interface{} // 操作系统   
    CreatedAt *gtime.Time // 登录时间   
}