// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-ruoyi/internal/service/internal/dao/internal"
)

// sysAaDao is the data access object for table sys_aa.
// You can define custom methods on it to extend its functionality as you wish.
type sysAaDao struct {
	*internal.SysAaDao
}

var (
	// SysAa is globally public accessible object for table sys_aa operations.
	SysAa = sysAaDao{
		internal.NewSysAaDao(),
	}
)

// Fill with you ideas below.