// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-ruoyi/internal/service/internal/dao/internal"
)

// sysFileDao is the data access object for table sys_file.
// You can define custom methods on it to extend its functionality as you wish.
type sysFileDao struct {
	*internal.SysFileDao
}

var (
	// SysFile is globally public accessible object for table sys_file operations.
	SysFile = sysFileDao{
		internal.NewSysFileDao(),
	}
)

// Fill with you ideas below.