// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. 
// =================================================================================

package do

import(
"github.com/gogf/gf/v2/frame/g"
"github.com/gogf/gf/v2/os/gtime"
)

// SysUserOnline is the golang structure of table sys_user_online for DAO operations like Where/Data.
type SysUserOnline struct {
g.Meta `orm:"table:sys_user_online, do:true"`
    Id interface{} //             
    Token interface{} // 用户token   
    UserId interface{} // 用户id      
    UserName interface{} // 用户名      
    Os interface{} // 操作系统    
    Ipaddr interface{} // 登录IP地址  
    LoginLocation interface{} // 登录地点    
    Browser interface{} // 浏览器类型  
    CreatedAt     *gtime.Time // 登录时间    
}