// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. 
// =================================================================================

package do

import(
"github.com/gogf/gf/v2/frame/g"
"github.com/gogf/gf/v2/os/gtime"
)

// SysRole is the golang structure of table sys_role for DAO operations like Where/Data.
type SysRole struct {
g.Meta `orm:"table:sys_role, do:true"`
    RoleId interface{} // 角色ID                    
    RoleName interface{} // 角色名称                  
    RoleKey interface{} // 权限字符                  
    RoleSort interface{} // 显示顺序                  
    Status interface{} // 角色状态；0:禁用，1:正常  
    Remark interface{} // 备注                      
    CreatedAt *gtime.Time // 创建时间                  
    UpdatedAt *gtime.Time // 更新时间                  
    DeletedAt *gtime.Time // 删除时间                  
}