// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. 
// =================================================================================

package entity

import(
"github.com/gogf/gf/v2/os/gtime"
)

// SysMenu is the golang structure for table sys_menu.
type SysMenu struct {
    MenuId    int         `json:"menuId"    `// 菜单ID                         
    MenuName  string      `json:"menuName"  `// 菜单名称                       
    ParentId  int         `json:"parentId"  `// 父菜单ID                       
    Sort      int         `json:"sort"      `// 排序标记                       
    Path      string      `json:"path"      `// 路由地址                       
    Component string      `json:"component" `// 组件路径                       
    IsFrame   string      `json:"isFrame"   `// 是否为外链（0是 1否）          
    IsCache   string      `json:"isCache"   `// 是否缓存（0缓存 1不缓存）      
    Query     string      `json:"query"     `// 路由参数                       
    MenuType  string      `json:"menuType"  `// 菜单类型（M目录 C菜单 F按钮）  
    Visible   string      `json:"visible"   `// 显示状态（0显示 1隐藏）        
    Status    string      `json:"status"    `// 菜单状态（0正常 1停用）        
    Perms     string      `json:"perms"     `// 权限标识                       
    Icon      string      `json:"icon"      `// 菜单图标                       
    CreatedAt *gtime.Time `json:"createdAt" `// 创建时间                       
    UpdatedAt *gtime.Time `json:"updatedAt" `// 更新时间                       
    DeletedAt *gtime.Time `json:"deletedAt" `// 删除时间                       
}