// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. 
// =================================================================================

package entity

import(
"github.com/gogf/gf/v2/os/gtime"
)

// SysUser is the golang structure for table sys_user.
type SysUser struct {
    UserId    uint        `json:"userId"    `// 用户ID                   
    UserName  string      `json:"userName"  `// 用户账号                 
    NickName  string      `json:"nickName"  `// 用户昵称                 
    Password  string      `json:"password"  `// 登录密码                 
    Mobile    string      `json:"mobile"    `// 手机号码                 
    Avatar    string      `json:"avatar"    `// 用户头像地址             
    Status    string      `json:"status"    `// 用户状态（0正常 1停用）  
    DeptId    int64       `json:"deptId"    `// 部门id                   
    Remark    string      `json:"remark"    `// 备注                     
    LoginIp   string      `json:"loginIp"   `// 最后登录IP               
    LoginDate *gtime.Time `json:"loginDate" `// 最后登录时间             
    CreatedAt *gtime.Time `json:"createdAt" `// 创建时间                 
    UpdatedAt *gtime.Time `json:"updatedAt" `// 更新时间                 
    DeletedAt *gtime.Time `json:"deletedAt" `// 删除时间                 
}