// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. 
// =================================================================================

package entity



// SysUserRole is the golang structure for table sys_user_role.
type SysUserRole struct {
    UserId int `json:"userId" `// 用户ID  
    RoleId int `json:"roleId" `// 角色ID  
}