// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. 
// =================================================================================

package entity



// SysRoleMenu is the golang structure for table sys_role_menu.
type SysRoleMenu struct {
    RoleId int `json:"roleId" `// 角色ID  
    MenuId int `json:"menuId" `// 菜单ID  
}