// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. 
// =================================================================================

package entity

import(
"github.com/gogf/gf/v2/os/gtime"
)

// SysJob is the golang structure for table sys_job.
type SysJob struct {
    JobId          int64       `json:"jobId"          `// 任务ID                                             
    JobName        string      `json:"jobName"        `// 任务名称                                           
    JobGroup       string      `json:"jobGroup"       `// 任务组名                                           
    InvokeTarget   string      `json:"invokeTarget"   `// 调用目标字符串                                     
    JobParams      string      `json:"jobParams"      `// 参数                                               
    CronExpression string      `json:"cronExpression" `// cron执行表达式                                     
    MisfirePolicy  string      `json:"misfirePolicy"  `// 计划执行错误策略（1立即执行 2执行一次 3放弃执行）  
    Status         string      `json:"status"         `// 状态（0正常 1暂停）                                
    Remark         string      `json:"remark"         `// 备注信息                                           
    CreatedAt      *gtime.Time `json:"createdAt"      `// 创建时间                                           
    UpdatedAt      *gtime.Time `json:"updatedAt"      `// 更新时间                                           
    DeletedAt      *gtime.Time `json:"deletedAt"      `// 删除时间                                           
}