// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SysRoleDao is the data access object for table sys_role.
type SysRoleDao struct {
	Table   string          // Table is the underlying table name of the DAO.
	Group   string          // Group is the database configuration group name of current DAO.
	Columns SysRoleColumns // Columns contains all the column names of Table for convenient usage.
}

// SysRoleColumns defines and stores column names for table sys_role.
type SysRoleColumns struct {
	RoleId     string // 角色ID                    
    RoleName   string // 角色名称                  
    RoleKey    string // 权限字符                  
    RoleSort   string // 显示顺序                  
    Status     string // 角色状态；0:禁用，1:正常  
    Remark     string // 备注                      
    CreatedAt  string // 创建时间                  
    UpdatedAt  string // 更新时间                  
    DeletedAt  string // 删除时间
}

//  sysRoleColumns holds the columns for table sys_role.
var sysRoleColumns = SysRoleColumns{
	RoleId:    "role_id",     
            RoleName:  "role_name",   
            RoleKey:   "role_key",    
            RoleSort:  "role_sort",   
            Status:    "status",      
            Remark:    "remark",      
            CreatedAt: "created_at",  
            UpdatedAt: "updated_at",  
            DeletedAt: "deleted_at",
}

// NewSysRoleDao creates and returns a new DAO object for table data access.
func NewSysRoleDao() *SysRoleDao {
	return &SysRoleDao{
		Group:   "default",
		Table:   "sys_role",
		Columns: sysRoleColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SysRoleDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SysRoleDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SysRoleDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}