// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SysUserDao is the data access object for table sys_user.
type SysUserDao struct {
	Table   string          // Table is the underlying table name of the DAO.
	Group   string          // Group is the database configuration group name of current DAO.
	Columns SysUserColumns // Columns contains all the column names of Table for convenient usage.
}

// SysUserColumns defines and stores column names for table sys_user.
type SysUserColumns struct {
	UserId     string // 用户ID                   
    UserName   string // 用户账号                 
    NickName   string // 用户昵称                 
    Password   string // 登录密码                 
    Mobile     string // 手机号                   
    Avatar     string // 用户头像地址             
    Status     string // 用户状态；0:禁用,1:正常  
    RoleIds    string // 角色id字符串             
    ShopIds    string // 店铺ID字符串             
    DeptId     string // 部门ID                   
    Remark     string // 备注                     
    CreatedAt  string // 创建时间                 
    UpdatedAt  string // 更新时间                 
    DeletedAt  string // 删除时间
}

//  sysUserColumns holds the columns for table sys_user.
var sysUserColumns = SysUserColumns{
	UserId:    "user_id",     
            UserName:  "user_name",   
            NickName:  "nick_name",   
            Password:  "password",    
            Mobile:    "mobile",      
            Avatar:    "avatar",      
            Status:    "status",      
            RoleIds:   "role_ids",    
            ShopIds:   "shop_ids",    
            DeptId:    "dept_id",     
            Remark:    "remark",      
            CreatedAt: "created_at",  
            UpdatedAt: "updated_at",  
            DeletedAt: "deleted_at",
}

// NewSysUserDao creates and returns a new DAO object for table data access.
func NewSysUserDao() *SysUserDao {
	return &SysUserDao{
		Group:   "default",
		Table:   "sys_user",
		Columns: sysUserColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SysUserDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SysUserDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SysUserDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}